name: TotalTracker
version: 1.20.0
author: bittiez
main: US.bittiez.TotalTracker.main
commands:
    tt:
        description: Various TotalTracker commands
        usage: /tt (reload | sync)
permissions:
    TotalTracker.sync:
        description: Allows the use of /tt sync
    TotalTracker.reload:
        description: Allows the use of /tt reload
    TotalTracker.updates:
        description: Will receive notifications when an update is available
        default: op