name: TotalTracker
version: 1.22.1
author: bittiez
main: US.bittiez.TotalTracker.main
commands:
    tt:
        description: Various TotalTracker commands
        usage: /tt (reload | sync)
permissions:
    TotalTracker.sync:
        description: Allows the use of /tt sync
    TotalTracker.reload:
        description: Allows the use of /tt reload
    TotalTracker.updates:
        description: Will receive notifications when an update is available
        default: op
    TotalTracker.cache:
        description: Will rebuild the total server counts for all stats, this may be resource heavy but it will be ran in a seperate thread. Do not do this often, it shouldn't be needed.